### ISSUE TITLE
"Invalid memory reference" when appending a row with a timestamp

### ISSUE THREAD

**Issue by danbruder** [wangfenjin/duckdb-rs#41]
Thanks for the crate! 

I'm trying to use the `Appender` api but get a segfault when there is a timestamp in the row. Here's a minimal example showing what happens (and here is a [repo](https://github.com/danbruder/duckdb-appender-issue/blob/e8a477453e8f2cf3c1b7f8c3de2b77ef85986fc6/src/lib.rs#L25) reproducing it):

```rust
    #[test]
    fn timestamp_appender_minimal_example_sig_segv() {
        let db = Connection::open_in_memory().unwrap();

        let create_table_sql = r"
          CREATE TABLE item (
              id INTEGER NOT NULL,
              ts TIMESTAMP
          );";
        db.execute_batch(create_table_sql).unwrap();

        let mut app = db.appender("item").unwrap();
        let row_count = 10;
        for i in 0..row_count {
            app.append_row(params![i, "1970-01-01T00:00:00Z"]).unwrap();
        }

        // running 1 test
        // error: test failed, to rerun pass '--lib'
        // Caused by:
        //   process didn't exit successfully: `/path-to-repo` (signal: 11, SIGSEGV: invalid memory reference)

        let val = db
            .query_row("SELECT count(1) FROM item", [], |row| {
                <(u32,)>::try_from(row)
            })
            .unwrap();

        assert_eq!(val, (row_count,));
    }
```

I've enabled the chrono feature and tried with `Utc::now` as well. This is using the `bundled` version of duckdb. 

I'd love to help fix the issue, would you mind pointing me in the right direction? I started a draft with failing tests [here](https://github.com/wangfenjin/duckdb-rs/pull/42)

**Comment by wangfenjin** [comment]
Hi @danbruder , thanks for the report! The root cause is currently we don't support bind timestamp param. It will not be an easy fix, but I'll give you some clue:

1. The most important change we need is to add support binding timestamp in [here](https://github.com/wangfenjin/duckdb-rs/blob/main/src/appender.rs#L110)
```rust
// this is simplified, we need to convert i according to timeunit u
ValueRef::Timestamp(u, i) => unsafe { ffi::duckdb_append_timestamp(ptr, ffi::duckdb_timestamp{micros: i}) }
```

2. Then we need support convert some rust data types into [Value type](https://github.com/wangfenjin/duckdb-rs/blob/main/src/types/value.rs#L162)
3. And also need to make this type impl [ToSql](https://github.com/wangfenjin/duckdb-rs/blob/main/src/types/to_sql.rs#L181)

We may change [chrono.rs](https://github.com/wangfenjin/duckdb-rs/blob/main/src/types/chrono.rs#L1) convert to Timestamp, currently it use String / Text

**Comment by wangfenjin** [comment]
Also I create an issue in https://github.com/duckdb/duckdb/pull/3402

If we can support append string as timestamp it will make us easier

**Comment by hawkfish** [comment]
It looks like the DuckDB C API appender does not cast strings to timestamps internally (it will try to cast it to an `int64_t`).
