### ISSUE TITLE
Add support for connection pool

### ISSUE THREAD

**Issue by wangfenjin** [wangfenjin/duckdb-rs#6]
Maybe use https://github.com/sfackler/r2d2

**Comment by jaredzhou** [comment]
Hi, i want to add a r2d2 connection pool to duckdb-rs, the problem is that when creating multiple connection, the Config need to be cloned multiple times, but duckdb_config can only be dropped once. I think we can use Arc<Option<ffi::duckdb_config>> for config instead, when the Arc strong_count is 1, we can call duckdb_destroy_config method. The problem is we need to change the Connection code with config as well, do you think it is a good idea? or do you have any suggestion @wangfenjin

**Comment by wangfenjin** [comment]
When we clone Config, can we also clone the inner duckdb_config? That way every connection's config is independent.

Thanks for your interests, I'll assign this issue to you. Happy to review the PR!

**Comment by jaredzhou** [comment]
yeah, clone duckdb_config can do the job, i will try it

**Comment by pricesmith** [comment]
Can someone show me how this is done?
