### ISSUE TITLE
Unable to compile `duckdb-sys` on Windows

### ISSUE THREAD

**Issue by Michael-F-Bryan** [wangfenjin/duckdb-rs#62]
We were setting up Windows builds in GitHub Actions for our app and noticed that the `duckdb-sys v0.4.0` crate's build script is unable to compile DuckDB from source.

There are a lot of suspicious warnings, and I've had to attach the output as a file because GitHub has a  65536 character limit on comments, but I think this is the thing that actually fails the build:

```
fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj
```

[(Link to full output from the build script)](https://github.com/wangfenjin/duckdb-rs/files/9007121/stderr.txt)

I notice you've actually commented out the Windows build for this repo's CI. Does that mean this is a known issue?

https://github.com/wangfenjin/duckdb-rs/blob/30d8e3e637f8a3f9b96ca6de9e2275bc69a5bbae/.github/workflows/rust.yaml#L15-L17

**Comment by wangfenjin** [comment]
Hi @Michael-F-Bryan , thanks for the report.

* I copy the CI scripts from other repo and comment out windows part because I'm not familiar with Windows and don't have time to debug the issue.
* You are suggested to download the released binary from duckdb repo like I do in [here](https://github.com/wangfenjin/duckdb-rs/blob/main/.github/workflows/rust.yaml#L38-L48) and link to them, instead of build it by yourself.
* If you are definitely want to build by yourself, you can still do it independently and then link to the binary. 

I don't mean we can't support windows build in our script, it takes time and effort. If you are interested you can help us solve this problem, I'm very willing to merge any PR.

**Comment by wangfenjin** [comment]
For the specific problems you reported, seems can be solved by add flags in [build.rs](https://github.com/wangfenjin/duckdb-rs/blob/main/libduckdb-sys/build.rs#L64)

https://docs.microsoft.com/en-us/cpp/build/reference/bigobj-increase-number-of-sections-in-dot-obj-file?view=msvc-170
